#!/usr/bin/env zsh
# @name: fe
# @description: Fuzzy file editor
# @category: file
# @keywords: fzf, file, edit, search
# @usage: fe [args]
# @example: fe

fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}
