#!/usr/bin/env zsh
# @name: fkill
# @description: Fuzzy process kill
# @category: system
# @keywords: kill, process, fzf, pkill
# @usage: fkill [args]
# @example: fkill

fkill() {
    local pid
    if [ "$UID" != "0" ]; then
        pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
    else
        pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
    fi

    if [ "x$pid" != "x" ]
    then
        echo $pid | xargs kill -${1:-9}
    fi
}
