#!/usr/bin/env zsh
# @name: da
# @description: Docker attach to container
# @category: docker
# @keywords: docker, attach, container
# @usage: da [args]
# @example: da

da() {
  local cid
  cid=$(docker ps -a | sed 1d | fzf -1 -q "$1" | awk '{print $1}')

  [ -n "$cid" ] && docker start "$cid" && docker attach "$cid"
}
