#!/usr/bin/env zsh
# @name: ds
# @description: Docker shell/exec into container
# @category: docker
# @keywords: docker, exec, shell
# @usage: ds [args]
# @example: ds

ds() {
  local cid
  cid=$(docker ps | sed 1d | fzf -q "$1" | awk '{print $1}')

  [ -n "$cid" ] && docker stop "$cid"
}
