#!/usr/bin/env zsh
# @name: rmwt
# @description: Remove git worktree
# @category: git
# @keywords: git, worktree, remove, delete
# @usage: rmwt [args]
# @example: rmwt

rmwt () {
  local target=$1

  # If no arg: are we *in* a work-tree folder that matches "<repo>-<branch>"?
  if [[ -z $target ]] && git rev-parse --git-path . &>/dev/null; then
    local root=$(git rev-parse --show-toplevel)
    local base=${root:t}
    [[ $base == *-* ]] && target=$root
  fi

  [[ -z $target ]] && { echo "Usage: rmwt [worktree-path]"; return 1 }
  ! git -C "$target" rev-parse --git-dir &>/dev/null && { echo "❌  $target is not a git dir"; return 1 }

  read -q "REPLY?⚠️  Remove work-tree $target ? [y/N] " || { echo; return 1 }
  echo

  # Change away from target directory if we're currently in it
  [[ "$(pwd)" == "$target"* ]] && cd ..

  git worktree remove --force "$target" && rm -rf "$target"
  echo "🗑  Work-tree removed"
}
