[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[env]
_.fnox-env = { tools = true }
# GITHUB_TOKEN = "{{exec(command='gh auth token')}}"
_.path = ["~/.bun/bin"]

[settings]
idiomatic_version_file_enable_tools = ["node"]
npm.bun = true

[tools]
age = "latest"
fnox = "latest"
bun = "latest"
go = "latest"
java = "21"
node = "24"
python = "latest"
rust = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
maven = "latest"
1password-cli = "latest"
"github:Microck/kagi-cli" = "0.5.2"
codex = "latest"
